name: GoGoGo

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: inst Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: chec
      uses: actions/checkout@v4
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
      
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: inst Go
      uses: actions/setup-go@v5
    - name: chec
      uses: actions/checkout@v4
    - name: lint
      run: go vet -v ./...

  tests:
    
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Test
      run: go test -v ./...

  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: |
          go vet ./...

  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: alekskag/43:v1

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 
