name: GoGoGo

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: inst Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - name: chec
      uses: actions/checkout@v4
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
      
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: inst Go
      uses: actions/setup-go@v5
    - name: chec
      uses: actions/checkout@v4
    - name: lint
      run: go vet -v ./...

  test: 
  needs: build
  runs-on: ubuntu-latest
    steps:
    - name: inst Go
      uses: actions/setup-go@v5
    - name: chec
      uses: actions/checkout@v4
    - name: lint
      run: go vet -v ./...
      
